### ISSUE TITLE
Not compile with 3.3.7

### ISSUE THREAD

**Issue by andromeda2911** [chegewara/EspTinyUSB#160]
Hi,
compiling sample code keyboard2 not compil with core 3.3.7

```
\libraries\EspTinyUSB-2.0.2\src\device\dfu\dfuusb.cpp:2:10: fatal error: soc/rtc_cntl_reg.h: No such file or directory
    2 | #include "soc/rtc_cntl_reg.h"
      |          ^~~~~~~~~~~~~~~~~~~~
```
Thanks
